//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// See LICENSE.txt for the text of the license.
//-----------------------------------------------------------------------------
// readline auto complete utilities
//-----------------------------------------------------------------------------

#ifndef PM3LINE_VOCABULARY_H__
#define PM3LINE_VOCABULARY_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>

typedef struct vocabulary_s {
    bool offline;
    const char *name;
} vocabulary_t;

const static vocabulary_t vocabulary[] = {
    { 1, "help" },
    { 0, "auto" },
    { 1, "清除" },
    { 1, "提示" },
    { 1, "毫秒睡眠" },
    { 1, "注释" },
    { 1, "退出" },
    { 1, "exit" },
    { 1, "prefs help" },
    { 1, "prefs 显示" },
    { 1, "prefs 获取 条模式" },
    { 1, "prefs 获取 客户端调试" },
    { 1, "prefs 获取 客户端延迟" },
    { 1, "prefs 获取 客户端超时" },
    { 1, "prefs 获取 高频场超时秒数" },
    { 1, "prefs 获取 颜色" },
    { 1, "prefs 获取 保存路径" },
    { 1, "prefs 获取 表情符号" },
    { 1, "prefs 获取 提示" },
    { 1, "prefs 获取 输出" },
    { 1, "prefs 获取 绘图滑块" },
    { 1, "prefs 获取 MQTT" },
    { 1, "prefs set help" },
    { 1, "prefs 设置 条模式" },
    { 1, "prefs 设置 客户端调试" },
    { 1, "prefs 设置 客户端延迟" },
    { 1, "prefs 设置 客户端超时" },
    { 1, "prefs 设置 高频场超时秒数" },
    { 1, "prefs 设置 颜色" },
    { 1, "prefs 设置 表情符号" },
    { 1, "prefs 设置 提示" },
    { 1, "prefs 设置 保存路径" },
    { 1, "prefs 设置 输出" },
    { 1, "prefs 设置 绘图滑块" },
    { 1, "prefs 设置 MQTT" },
    { 1, "analyse help" },
    { 1, "分析 LRC" },
    { 1, "分析 CRC" },
    { 1, "分析校验和" },
    { 1, "分析日期" },
    { 1, "分析 LFSR" },
    { 1, "分析 a" },
    { 1, "分析 NUID" },
    { 1, "分析演示缓冲区" },
    { 1, "分析频率" },
    { 1, "分析 foo" },
    { 1, "分析正则表达式" },
    { 1, "分析单位" },
    { 1, "data help" },
    { 1, "数据清除" },
    { 1, "数据 隐藏" },
    { 1, "数据 加载" },
    { 1, "数据 数值" },
    { 1, "数据 绘图" },
    { 1, "数据 打印" },
    { 1, "数据保存" },
    { 1, "数据设置调试模式" },
    { 1, "数据异或" },
    { 1, "数据双相原始解码" },
    { 1, "数据 检测时钟" },
    { 1, "数据 FSK转NRZ" },
    { 1, "数据 曼彻斯特原始解码" },
    { 1, "数据 调制" },
    { 1, "数据 原始解调" },
    { 1, "数据 ASK 边沿检测" },
    { 1, "数据自相关" },
    { 1, "数据 转换比特流" },
    { 1, "数据 相关阈值" },
    { 1, "数据 脏阈值" },
    { 1, "数据 抽取" },
    { 1, "数据 包络" },
    { 1, "数据 网格" },
    { 1, "数据 获取比特流" },
    { 1, "数据 高通滤波" },
    { 1, "数据 IIR滤波" },
    { 1, "数据 左修剪" },
    { 1, "数据 多修剪" },
    { 1, "数据 归一化" },
    { 1, "数据右修剪" },
    { 1, "数据设置图形标记" },
    { 1, "数据平移图形零点" },
    { 1, "数据时间缩放" },
    { 1, "数据反抽取" },
    { 1, "数据过零点" },
    { 1, "数据 ASN1" },
    { 1, "数据 ATR" },
    { 0, "数据位采样" },
    { 1, "数据位图" },
    { 1, "数据 加密" },
    { 1, "数据 差分" },
    { 0, "数据 十六进制样本" },
    { 0, "数据采样" },
    { 1, "数据 二维码" },
    { 0, "数据测试_ss8" },
    { 0, "数据测试_ss32" },
    { 0, "数据测试_ss32s" },
    { 1, "emv help" },
    { 1, "emv list" },
    { 1, "EMV 测试" },
    { 0, "EMV 挑战" },
    { 0, "EMV 执行" },
    { 0, "EMV 生成应用密码" },
    { 0, "EMV 获取处理选项" },
    { 0, "EMV 内部认证" },
    { 0, "EMV 支付系统环境" },
    { 0, "EMV 读卡器" },
    { 0, "EMV 读取记录" },
    { 0, "EMV ROCA" },
    { 0, "EMV 扫描" },
    { 0, "EMV 搜索" },
    { 0, "EMV 选择" },
    { 0, "EMV 智能卡转NFC" },
    { 1, "hf help" },
    { 1, "hf list" },
    { 0, "hf plot" },
    { 0, "hf 调谐" },
    { 1, "高频搜索" },
    { 0, "高频嗅探" },
    { 1, "hf 14a help" },
    { 1, "hf 14a list" },
    { 0, "hf 14a 防冲突测试" },
    { 0, "hf 14a 配置" },
    { 0, "hf 14a 自定义UID" },
    { 0, "hf 14a 信息" },
    { 0, "hf 14a 模拟" },
    { 0, "hf 14a 模拟AID" },
    { 0, "hf 14a 嗅探" },
    { 0, "hf 14a 原始命令" },
    { 0, "hf 14a 读卡器" },
    { 0, "hf 14a APDU" },
    { 0, "hf 14a APDU查找" },
    { 0, "hf 14a 链式操作" },
    { 0, "hf 14a NDEF格式化" },
    { 0, "hf 14a NDEF读取" },
    { 0, "hf 14a NDEF写入" },
    { 1, "hf 14b help" },
    { 0, "hf 14b 配置" },
    { 1, "hf 14b list" },
    { 0, "hf 14b APDU" },
    { 0, "hf 14b 转储" },
    { 0, "hf 14b 信息" },
    { 0, "hf 14b NDEF读取" },
    { 0, "hf 14b 原始命令" },
    { 0, "hf 14b 读取块" },
    { 0, "hf 14b 读卡器" },
    { 0, "hf 14b 恢复" },
    { 0, "hf 14b 模拟" },
    { 0, "hf 14b 嗅探" },
    { 0, "hf 14b 写块" },
    { 0, "hf 14b 撕卡" },
    { 1, "hf 14b 查看" },
    { 1, "hf 14b 验证" },
    { 0, "hf 14b Calypso" },
    { 0, "hf 14b MoBIB" },
    { 0, "hf 14b 设置UID" },
    { 1, "hf 15 help" },
    { 1, "hf 15 list" },
    { 1, "hf 15 解调" },
    { 0, "hf 15 转储" },
    { 0, "hf 15 信息" },
    { 0, "hf 15 嗅探" },
    { 0, "hf 15 原始命令" },
    { 0, "hf 15 读块" },
    { 0, "hf 15 多块读取" },
    { 0, "hf 15 读卡器模式" },
    { 0, "hf 15 恢复" },
    { 0, "hf 15 采样" },
    { 1, "hf 15 查看" },
    { 0, "hf 15 擦除" },
    { 0, "hf 15 写块" },
    { 0, "hf 15 模拟" },
    { 0, "hf 15 加载EEPROM" },
    { 0, "hf 15 保存EEPROM" },
    { 0, "hf 15 查看EEPROM" },
    { 0, "hf 15 SLIX写入密码" },
    { 0, "hf 15 禁用SLIX EAS" },
    { 0, "hf 15 启用SLIX EAS" },
    { 0, "hf 15 禁用SLIX隐私" },
    { 0, "hf 15 启用SLIX隐私" },
    { 0, "hf 15 SLIX保护页" },
    { 0, "hf 15 密码保护AFI" },
    { 0, "hf 15 密码保护EAS" },
    { 0, "hf 15 查找AFI" },
    { 0, "hf 15 写入AFI" },
    { 0, "hf 15 写入DSFID" },
    { 0, "hf 15 设置UID" },
    { 1, "hf aliro help" },
    { 1, "hf aliro list" },
    { 0, "hf aliro 信息" },
    { 0, "hf aliro 读取" },
    { 1, "hf cipurse help" },
    { 0, "hf cipurse 信息" },
    { 0, "hf cipurse 选择" },
    { 0, "hf cipurse 认证" },
    { 0, "hf cipurse 读取" },
    { 0, "hf cipurse 写入" },
    { 0, "hf cipurse 认证读取" },
    { 0, "hf cipurse 认证写入" },
    { 0, "hf cipurse 全部格式化" },
    { 0, "hf cipurse 创建" },
    { 0, "hf cipurse 删除" },
    { 0, "hf cipurse 更新密钥" },
    { 0, "hf cipurse 更新密钥" },
    { 0, "hf cipurse 默认" },
    { 1, "hf cipurse 测试" },
    { 1, "hf epa help" },
    { 0, "hf epa 挑战随机数" },
    { 0, "hf epa 重放" },
    { 0, "hf epa 仿真" },
    { 1, "hf emrtd help" },
    { 0, "hf emrtd 转储" },
    { 1, "hf emrtd 信息" },
    { 1, "hf emrtd list" },
    { 1, "hf felica help" },
    { 1, "hf felica list" },
    { 0, "hf felica 信息" },
    { 0, "hf felica SEAC信息" },
    { 0, "hf felica 原始命令" },
    { 0, "hf felica 读块" },
    { 0, "hf felica 读卡器" },
    { 0, "hf felica 嗅探" },
    { 0, "hf felica 写块" },
    { 0, "hf felica 转储" },
    { 0, "hf felica 发现节点" },
    { 0, "hf felica 请求服务" },
    { 0, "hf felica 请求响应" },
    { 0, "hf felica SCSV代码" },
    { 0, "hf felica 请求系统代码" },
    { 0, "hf felica 认证1" },
    { 0, "hf felica 认证2" },
    { 0, "hf felica 请求规格版本" },
    { 0, "hf felica 重置模式" },
    { 0, "hf felica 精简模拟" },
    { 0, "hf felica 精简认证" },
    { 0, "hf felica 精简转储" },
    { 1, "hf fido help" },
    { 1, "hf fido list" },
    { 0, "hf fido 信息" },
    { 0, "hf fido 注册" },
    { 0, "hf fido 认证" },
    { 0, "hf fido 生成" },
    { 0, "hf fido 断言" },
    { 1, "hf fudan help" },
    { 0, "hf fudan 读卡器" },
    { 0, "hf fudan 转储" },
    { 0, "hf fudan 读块" },
    { 1, "hf fudan 查看" },
    { 0, "hf fudan 写块" },
    { 1, "hf gallagher help" },
    { 0, "hf gallagher 读取器" },
    { 0, "hf gallagher 克隆" },
    { 0, "hf gallagher 删除" },
    { 1, "hf gallagher diversifykey" },
    { 1, "hf gallagher 解码" },
    { 1, "hf gallagher 编码" },
    { 1, "hf gallagher 测试" },
    { 1, "hf gst help" },
    { 1, "hf gst list" },
    { 1, "hf gst 测试" },
    { 0, "hf gst 信息" },
    { 0, "hf gst 读取" },
    { 1, "hf secc help" },
    { 0, "高频SECC信息" },
    { 0, "高频SECC模拟" },
    { 0, "高频SECC嗅探" },
    { 1, "hf iclass help" },
    { 1, "hf iclass list" },
    { 0, "hf iclass 转储" },
    { 0, "hf iclass 信息" },
    { 0, "hf iclass 读块" },
    { 0, "hf iclass 读卡器" },
    { 0, "hf iclass 恢复" },
    { 0, "hf iclass 嗅探" },
    { 1, "hf iclass 查看" },
    { 0, "hf iclass 写块" },
    { 0, "hf iclass 充值钱包" },
    { 0, "hf iclass 撕毁" },
    { 0, "hf iclass 检查" },
    { 1, "hf iclass loclass" },
    { 1, "hf iclass 查找" },
    { 0, "hf iclass 恢复" },
    { 1, "hf iclass 暴力破解" },
    { 1, "hf iclass 去哈希" },
    { 0, "hf iclass blacktears" },
    { 0, "hf iclass 模拟" },
    { 0, "hf iclass 标签模拟" },
    { 0, "hf iclass 加载" },
    { 0, "hf iclass 保存" },
    { 0, "hf iclass 设置块" },
    { 0, "hf iclass 查看" },
    { 0, "hf iclass 配置卡" },
    { 1, "hf iclass 计算新密钥" },
    { 1, "hf iclass 编码" },
    { 1, "hf iclass 加密" },
    { 1, "hf iclass 解密" },
    { 1, "hf iclass 管理密钥" },
    { 1, "hf iclass 密钥置换" },
    { 0, "hf iclass SAM" },
    { 1, "hf ict help" },
    { 0, "hf ict 凭证" },
    { 0, "hf ict 信息" },
    { 1, "hf ict list" },
    { 1, "hf ict 读卡器" },
    { 1, "hf jooki help" },
    { 0, "hf jooki 克隆" },
    { 1, "hf jooki 解码" },
    { 1, "hf jooki 编码" },
    { 0, "hf jooki 模拟" },
    { 1, "hf ksx6924 help" },
    { 0, "hf ksx6924 选择" },
    { 0, "hf ksx6924 信息" },
    { 0, "hf ksx6924 余额" },
    { 0, "hf ksx6924 初始化" },
    { 0, "hf ksx6924 精度" },
    { 1, "hf legic help" },
    { 0, "hf legic 转储" },
    { 0, "hf legic 信息" },
    { 1, "hf legic list" },
    { 0, "hf legic 读块" },
    { 0, "hf legic 读取器" },
    { 0, "hf legic 恢复" },
    { 0, "hf legic 擦除" },
    { 0, "hf legic 写块" },
    { 0, "hf legic 模拟" },
    { 0, "hf legic 扩展加载" },
    { 0, "hf legic 扩展保存" },
    { 0, "hf legic 扩展查看" },
    { 0, "hf legic 扩展信息" },
    { 1, "hf legic CRC" },
    { 1, "hf legic 查看" },
    { 1, "hf lto help" },
    { 0, "hf lto 转储" },
    { 0, "hf lto 信息" },
    { 1, "hf lto list" },
    { 0, "hf lto 读块" },
    { 0, "hf lto 读取器" },
    { 0, "hf lto 恢复" },
    { 0, "hf lto 写块" },
    { 1, "hf mf help" },
    { 1, "hf mf list" },
    { 0, "hf mf 暗侧攻击" },
    { 0, "hf mf nested" },
    { 1, "hf mf hardnested" },
    { 0, "hf mf staticnested" },
    { 0, "hf mf 暴力破解" },
    { 0, "hf mf 自动破解" },
    { 0, "hf mf nack" },
    { 0, "hf mf 检查" },
    { 0, "hf mf fchk" },
    { 1, "hf mf 解密" },
    { 0, "hf mf supercard" },
    { 1, "hf mf keygen" },
    { 0, "hf mf 认证4" },
    { 1, "hf mf 访问控制列表" },
    { 0, "hf mf 转储" },
    { 0, "hf mf info" },
    { 0, "hf mf isen" },
    { 1, "hf mf mad" },
    { 0, "hf mf personalize" },
    { 0, "hf mf rdbl" },
    { 0, "hf mf rdsc" },
    { 0, "hf mf restore" },
    { 0, "hf mf setmod" },
    { 1, "hf mf value" },
    { 1, "hf mf view" },
    { 0, "hf mf wipe" },
    { 0, "hf mf wrbl" },
    { 0, "hf mf sim" },
    { 0, "hf mf ecfill" },
    { 0, "hf mf eclr" },
    { 0, "hf mf egetblk" },
    { 0, "hf mf egetsc" },
    { 0, "hf mf ekeyprn" },
    { 0, "hf mf eload" },
    { 0, "hf mf esave" },
    { 0, "hf mf esetblk" },
    { 0, "hf mf eview" },
    { 0, "hf mf 获取块" },
    { 0, "hf mf 获取扇区" },
    { 0, "hf mf 加载" },
    { 0, "hf mf 保存" },
    { 0, "hf mf 设置块" },
    { 0, "hf mf 设置UID" },
    { 0, "hf mf 查看" },
    { 0, "hf mf 擦除" },
    { 0, "hf mf gen3uid" },
    { 0, "hf mf gen3blk" },
    { 0, "hf mf gen3freeze" },
    { 1, "hf mf ginfo" },
    { 0, "hf mf ggetblk" },
    { 0, "hf mf gload" },
    { 0, "hf mf gsave" },
    { 0, "hf mf gsetblk" },
    { 0, "hf mf gview" },
    { 0, "hf mf gchpwd" },
    { 0, "hf mf gdmcfg" },
    { 0, "hf mf gdmsetcfg" },
    { 1, "hf mf gdmparsecfg" },
    { 0, "hf mf gdmsetblk" },
    { 0, "hf mf ndefformat" },
    { 0, "hf mf ndefread" },
    { 0, "hf mf ndefwrite" },
    { 0, "hf mf encodehid" },
    { 1, "hf mfp help" },
    { 1, "hf mfp list" },
    { 1, "hf mfp ACL" },
    { 0, "hf mfp 认证" },
    { 0, "hf mfp 检查密钥" },
    { 0, "hf mfp 转储" },
    { 0, "hf mfp 信息" },
    { 0, "hf mfp MAD" },
    { 0, "hf mfp 读取块" },
    { 0, "hf mfp 读取扇区" },
    { 0, "hf mfp 写入块" },
    { 0, "hf mfp 更改密钥" },
    { 0, "hf mfp 检查配置" },
    { 0, "hf mfp 提交持久化" },
    { 0, "hf mfp 初始化持久化" },
    { 0, "hf mfp 写入持久化" },
    { 0, "hf mfp NDEF 格式化" },
    { 0, "hf mfp NDEF 读取" },
    { 0, "hf mfp NDEF 写入" },
    { 1, "hf mfu help" },
    { 1, "hf mfu list" },
    { 1, "hf mfu 密钥生成" },
    { 1, "hf mfu pwdgen" },
    { 0, "hf mfu otptear" },
    { 0, "hf mfu 计数器撕裂" },
    { 0, "hf mfu 计数器认证" },
    { 0, "hf mfu 计数器检查" },
    { 0, "hf mfu AES 认证" },
    { 0, "hf mfu AES 检查" },
    { 0, "hf mfu setkey" },
    { 0, "hf mfu 转储" },
    { 0, "hf mfu 递增" },
    { 0, "hf mfu 信息" },
    { 0, "hf mfu NDEF 读取" },
    { 0, "hf mfu rdbl" },
    { 0, "hf mfu restore" },
    { 0, "hf mfu tamper" },
    { 1, "hf mfu view" },
    { 0, "hf mfu wipe" },
    { 0, "hf mfu wrbl" },
    { 0, "hf mfu 加载EEPROM" },
    { 0, "hf mfu 保存EEPROM" },
    { 0, "hf mfu 查看EEPROM" },
    { 0, "hf mfu sim" },
    { 0, "hf mfu setuid" },
    { 0, "hf mfu Amiibo" },
    { 1, "hf mfdes help" },
    { 1, "hf mfdes list" },
    { 0, "hf mfdes auth" },
    { 0, "hf mfdes chk" },
    { 0, "hf mfdes 默认" },
    { 0, "hf mfdes 检测" },
    { 0, "hf mfdes 格式化PICC" },
    { 0, "hf mfdes freemem" },
    { 0, "hf mfdes 获取UID" },
    { 0, "hf mfdes 信息" },
    { 0, "hf mfdes MAD" },
    { 0, "hf mfdes 设置配置" },
    { 0, "hf mfdes 列出应用" },
    { 0, "hf mfdes 获取AID" },
    { 0, "hf mfdes 获取应用名称" },
    { 0, "hf mfdes bruteaid" },
    { 0, "hf mfdes brutedamslot" },
    { 0, "hf mfdes createapp" },
    { 0, "hf mfdes createdelegateapp" },
    { 0, "hf mfdes 获取委托应用信息" },
    { 0, "hf mfdes 删除应用" },
    { 0, "hf mfdes 选择应用" },
    { 0, "hf mfdes 选择ISO FID" },
    { 0, "hf mfdes changekey" },
    { 0, "hf mfdes chkeysettings" },
    { 0, "hf mfdes 获取密钥设置" },
    { 0, "hf mfdes 获取密钥版本" },
    { 0, "hf mfdes bruteisofid" },
    { 0, "hf mfdes 获取文件ID" },
    { 0, "hf mfdes 获取文件ISO ID" },
    { 0, "hf mfdes 列出文件" },
    { 0, "hf mfdes 转储" },
    { 0, "hf mfdes createfile" },
    { 0, "hf mfdes 创建值文件" },
    { 0, "hf mfdes 创建记录文件" },
    { 0, "hf mfdes createmacfile" },
    { 0, "hf mfdes 删除文件" },
    { 0, "hf mfdes 获取文件设置" },
    { 0, "hf mfdes chfilesettings" },
    { 0, "hf mfdes 读取" },
    { 0, "hf mfdes 写入" },
    { 0, "hf mfdes 值" },
    { 0, "hf mfdes clearrecfile" },
    { 1, "hf mfdes 测试" },
    { 1, "hf ntag424 help" },
    { 0, "hf ntag424 info" },
    { 1, "hf ntag424 view" },
    { 0, "hf ntag424 auth" },
    { 0, "hf ntag424 read" },
    { 0, "hf ntag424 write" },
    { 0, "hf ntag424 getfs" },
    { 0, "hf ntag424 changefs" },
    { 0, "hf ntag424 changekey" },
    { 1, "hf saflok help" },
    { 0, "hf saflok read" },
    { 0, "hf saflok provision" },
    { 1, "hf saflok encode" },
    { 1, "hf saflok decode" },
    { 1, "hf saflok modify" },
    { 1, "hf saflok encrypt" },
    { 1, "hf saflok decrypt" },
    { 0, "hf saflok interrogate" },
    { 0, "hf saflok cksum" },
    { 1, "hf saflok selftest" },
    { 1, "hf seos help" },
    { 1, "hf seos list" },
    { 0, "高频SEOS SAM" },
    { 0, "高频SEOS信息" },
    { 0, "高频SEOS PACS" },
    { 0, "高频SEOS写入" },
    { 0, "高频SEOS ADF" },
    { 0, "高频SEOS GDF" },
    { 0, "高频SEOS模拟" },
    { 1, "高频SEOS密钥管理" },
    { 1, "hf st25ta help" },
    { 0, "高频ST25TA信息" },
    { 1, "hf st25ta list" },
    { 1, "高频ST25TA NDEF读取" },
    { 0, "高频ST25TA保护" },
    { 0, "高频ST25TA密码" },
    { 0, "高频ST25TA模拟" },
    { 1, "hf tesla help" },
    { 0, "hf tesla info" },
    { 1, "hf tesla list" },
    { 1, "hf texkom help" },
    { 0, "高频TEXKOM读取器" },
    { 0, "高频TEXKOM模拟" },
    { 1, "hf thinfilm help" },
    { 0, "高频薄膜信息" },
    { 1, "hf thinfilm list" },
    { 0, "高频薄膜模拟" },
    { 1, "hf topaz help" },
    { 1, "hf topaz list" },
    { 0, "高频TOPAZ转储" },
    { 0, "高频TOPAZ信息" },
    { 0, "高频TOPAZ原始" },
    { 0, "高频TOPAZ读取块" },
    { 0, "高频TOPAZ读取器" },
    { 0, "高频TOPAZ模拟" },
    { 0, "高频TOPAZ嗅探" },
    { 1, "hf topaz 查看" },
    { 0, "hf topaz 写块" },
    { 1, "hf vas help" },
    { 0, "hf vas 信息" },
    { 0, "hf vas 读取器" },
    { 1, "hf vas 解密" },
    { 1, "hf waveshare help" },
    { 1, "hf waveshare 加载" },
    { 1, "hf xerox help" },
    { 1, "hf xerox list" },
    { 0, "hf xerox 信息" },
    { 0, "hf xerox 转储" },
    { 0, "hf xerox 读取器" },
    { 1, "hf xerox 查看" },
    { 0, "hf xerox 读块" },
    { 1, "hw help" },
    { 0, "硬件 检测读取器" },
    { 0, "硬件 状态" },
    { 0, "硬件撕脱" },
    { 1, "硬件超时" },
    { 1, "硬件版本" },
    { 0, "硬件 中断" },
    { 0, "硬件 引导加载程序" },
    { 1, "硬件 连接" },
    { 0, "硬件 调试" },
    { 0, "硬件 FPGA关闭" },
    { 0, "硬件 LCD" },
    { 0, "硬件 LCD重置" },
    { 0, "硬件 Ping" },
    { 0, "硬件 读内存" },
    { 0, "硬件 重置" },
    { 0, "硬件 设置低频分频器" },
    { 0, "硬件 设置高频阈值" },
    { 0, "硬件 设置多路复用器" },
    { 0, "硬件 独立模式" },
    { 0, "硬件TIA" },
    { 0, "硬件调谐" },
    { 0, "硬件 衰减" },
    { 1, "lf help" },
    { 0, "低频配置" },
    { 0, "低频命令读取" },
    { 0, "低频读取" },
    { 0, "低频中继" },
    { 1, "低频搜索" },
    { 0, "低频模拟" },
    { 0, "低频模拟ASK" },
    { 0, "低频模拟FSK" },
    { 0, "低频模拟PSK" },
    { 0, "低频模拟双向" },
    { 0, "低频嗅探" },
    { 0, "低频调谐" },
    { 1, "lf awid help" },
    { 0, "低频AWID暴力破解" },
    { 0, "低频AWID克隆" },
    { 1, "低频AWID解调" },
    { 0, "低频AWID读取器" },
    { 0, "低频AWID模拟" },
    { 0, "低频AWID监视" },
    { 1, "lf cotag help" },
    { 1, "低频Cotag解调" },
    { 0, "低频Cotag读取器" },
    { 1, "lf destron help" },
    { 1, "低频Destron解调" },
    { 0, "低频Destron读取器" },
    { 0, "低频Destron克隆" },
    { 0, "低频Destron模拟" },
    { 1, "lf em help" },
    { 1, "lf em 410x help" },
    { 1, "低频EM 410x解调" },
    { 0, "低频EM 410x读取器" },
    { 0, "低频EM 410x模拟" },
    { 0, "低频EM 410x暴力破解" },
    { 0, "低频EM 410x监视" },
    { 0, "低频EM 410x欺骗" },
    { 0, "低频EM 410x克隆" },
    { 1, "lf em 4x05 help" },
    { 0, "低频EM 4x05克隆帮助" },
    { 0, "低频EM 4x05暴力破解" },
    { 0, "低频EM 4x05检查" },
    { 1, "低频EM 4x05配置" },
    { 1, "lf em 4x05 解调" },
    { 0, "lf em 4x05 转储" },
    { 0, "lf em 4x05 信息" },
    { 0, "lf em 4x05 读取" },
    { 1, "lf em 4x05 嗅探" },
    { 0, "lf em 4x05 解锁" },
    { 1, "lf em 4x05 查看" },
    { 0, "lf em 4x05 擦除" },
    { 0, "lf em 4x05 写入" },
    { 1, "lf em 4x50 help" },
    { 0, "lf em 4x50 暴力破解" },
    { 0, "lf em 4x50 检查" },
    { 0, "lf em 4x50 转储" },
    { 0, "lf em 4x50 信息" },
    { 0, "lf em 4x50 登录" },
    { 0, "lf em 4x50 读块" },
    { 0, "lf em 4x50 读取器" },
    { 0, "lf em 4x50 恢复" },
    { 1, "lf em 4x50 查看" },
    { 0, "lf em 4x50 擦除" },
    { 0, "lf em 4x50 写块" },
    { 0, "lf em 4x50 写密码" },
    { 0, "lf em 4x50 加载EEPROM" },
    { 0, "lf em 4x50 保存EEPROM" },
    { 0, "lf em 4x50 查看EEPROM" },
    { 0, "lf em 4x50 模拟" },
    { 1, "lf em 4x70 help" },
    { 0, "lf em 4x70 暴力破解" },
    { 0, "lf em 4x70 信息" },
    { 0, "低频 EM 4x70 写入" },
    { 0, "低频 EM 4x70 解锁" },
    { 0, "lf em 4x70 认证" },
    { 0, "低频 EM 4x70 设置PIN" },
    { 0, "低频 EM 4x70 设置密钥" },
    { 1, "lf em 4x70 计算" },
    { 1, "低频 EM 4x70 恢复" },
    { 0, "lf em 4x70 自动恢复" },
    { 1, "lf fdxb help" },
    { 1, "低频 FDXB 解调" },
    { 0, "低频 FDXB 读取" },
    { 0, "低频 FDXB 克隆" },
    { 0, "低频 FDXB 模拟" },
    { 1, "lf gallagher help" },
    { 1, "低频 Gallagher 解调" },
    { 0, "低频 Gallagher 读取" },
    { 0, "低频 Gallagher 克隆" },
    { 0, "低频 Gallagher 模拟" },
    { 1, "lf gproxii help" },
    { 1, "低频 GProxII 解调" },
    { 0, "低频 GProxII 读取" },
    { 0, "低频 GProxII 克隆" },
    { 0, "低频 GProxII 模拟" },
    { 1, "lf hid help" },
    { 1, "低频 HID 解调" },
    { 0, "低频 HID 读取" },
    { 0, "低频 HID 克隆" },
    { 0, "低频 HID 模拟" },
    { 0, "低频 HID 暴力破解" },
    { 0, "低频 HID 监视" },
    { 1, "lf hitag help" },
    { 1, "lf hitag list" },
    { 0, "lf hitag 信息" },
    { 0, "lf hitag 读取器" },
    { 1, "lf hitag 测试" },
    { 0, "低频 Hitag 转储" },
    { 0, "lf hitag 读取" },
    { 0, "lf hitag 嗅探" },
    { 1, "lf hitag 查看" },
    { 0, "lf hitag 写块" },
    { 0, "低频 Hitag 电子加载" },
    { 0, "低频 Hitag 电子查看" },
    { 0, "lf hitag 模拟" },
    { 0, "低频 Hitag 挑战-响应" },
    { 0, "低频 Hitag 破解2" },
    { 0, "低频 Hitag 检查" },
    { 1, "lf hitag 查找" },
    { 0, "lf hitag TA" },
    { 1, "lf hitag hts help" },
    { 1, "lf hitag hts list" },
    { 0, "lf hitag hts 读取器" },
    { 0, "lf hitag hts 读块" },
    { 0, "低频 Hitag HTS 转储" },
    { 0, "lf hitag hts 恢复" },
    { 0, "lf hitag hts 写块" },
    { 0, "lf hitag hts 模拟" },
    { 1, "lf hitag htu help" },
    { 1, "lf hitag htu list" },
    { 0, "lf hitag htu 读取器" },
    { 0, "lf hitag htu 读块" },
    { 0, "lf hitag htu 转储" },
    { 0, "lf hitag htu 写块" },
    { 0, "lf hitag htu 模拟" },
    { 1, "lf idteck help" },
    { 1, "lf idteck 解调" },
    { 0, "lf idteck 读取器" },
    { 0, "lf idteck 克隆" },
    { 0, "lf idteck 模拟" },
    { 1, "lf indala help" },
    { 0, "lf indala 暴力破解" },
    { 1, "lf indala 解调" },
    { 1, "lf indala 备用解调" },
    { 0, "lf indala 读取器" },
    { 0, "lf indala 克隆" },
    { 0, "低频 Indala 模拟" },
    { 1, "lf io help" },
    { 1, "低频 IO 解调" },
    { 0, "低频 IO 读取" },
    { 0, "低频 IO 克隆" },
    { 0, "低频 IO 模拟" },
    { 0, "低频 IO 监视" },
    { 1, "lf jablotron help" },
    { 1, "低频 Jablotron 解调" },
    { 0, "低频 Jablotron 读取" },
    { 0, "低频 Jablotron 克隆" },
    { 0, "低频 Jablotron 模拟" },
    { 1, "lf keri help" },
    { 1, "低频 Keri 解调" },
    { 0, "低频 Keri 读取" },
    { 0, "低频 Keri 克隆" },
    { 0, "低频 Keri 模拟" },
    { 1, "lf motorola help" },
    { 1, "低频 Motorola 解调" },
    { 0, "低频 Motorola 读取" },
    { 0, "低频 Motorola 克隆" },
    { 0, "低频 Motorola 模拟" },
    { 1, "lf nedap help" },
    { 1, "低频 Nedap 解调" },
    { 0, "低频 Nedap 读取" },
    { 0, "低频 Nedap 克隆" },
    { 0, "低频 Nedap 模拟" },
    { 1, "lf nexwatch help" },
    { 1, "低频 Nexwatch 解调" },
    { 0, "低频 Nexwatch 读取" },
    { 0, "低频 Nexwatch 克隆" },
    { 0, "低频 Nexwatch 模拟" },
    { 1, "lf noralsy help" },
    { 1, "低频 Noralsy 解调" },
    { 0, "低频 Noralsy 读取" },
    { 0, "低频 Noralsy 克隆" },
    { 0, "低频 Noralsy 模拟" },
    { 1, "lf pac help" },
    { 1, "低频PAC解调" },
    { 0, "低频PAC读取器" },
    { 0, "低频PAC克隆" },
    { 0, "低频PAC模拟" },
    { 1, "lf paradox help" },
    { 1, "低频Paradox解调" },
    { 0, "低频Paradox读取器" },
    { 0, "低频Paradox克隆" },
    { 0, "低频Paradox模拟" },
    { 1, "lf pcf7931 help" },
    { 0, "低频PCF7931读取器" },
    { 0, "低频PCF7931写入" },
    { 1, "低频PCF7931配置" },
    { 1, "lf presco help" },
    { 1, "低频Presco解调" },
    { 0, "低频Presco读取器" },
    { 0, "低频Presco克隆" },
    { 0, "低频Presco模拟" },
    { 1, "lf pyramid help" },
    { 1, "低频Pyramid解调" },
    { 0, "低频Pyramid读取器" },
    { 0, "低频Pyramid克隆" },
    { 0, "低频Pyramid模拟" },
    { 1, "lf securakey help" },
    { 1, "低频Securakey解调" },
    { 0, "低频Securakey读取器" },
    { 0, "低频Securakey克隆" },
    { 0, "低频Securakey模拟" },
    { 1, "lf ti help" },
    { 1, "低频TI解调" },
    { 0, "低频TI读取器" },
    { 0, "低频TI写入" },
    { 1, "lf t55xx help" },
    { 0, "低频T55xx克隆帮助" },
    { 1, "低频T55xx配置" },
    { 0, "低频T55xx危险原始操作" },
    { 1, "低频T55xx检测" },
    { 0, "低频T55xx设备配置" },
    { 0, "低频T55xx转储" },
    { 1, "低频T55xx信息" },
    { 0, "低频T55xx页面1检测" },
    { 0, "低频T55xx读取" },
    { 0, "低频T55xx重置读取" },
    { 0, "低频T55xx恢复" },
    { 1, "低频T55xx追踪" },
    { 0, "低频T55xx唤醒" },
    { 1, "低频T55xx查看" },
    { 0, "低频T55xx写入" },
    { 0, "低频T55xx暴力破解" },
    { 0, "低频T55xx检测" },
    { 0, "低频T55xx保护" },
    { 0, "低频T55xx恢复密码" },
    { 1, "低频T55xx嗅探" },
    { 0, "低频T55xx特殊操作" },
    { 0, "低频T55xx擦除" },
    { 1, "lf viking help" },
    { 1, "低频Viking解调" },
    { 0, "低频维京读取器" },
    { 0, "低频Viking克隆" },
    { 0, "低频维京模拟" },
    { 1, "lf visa2000 help" },
    { 1, "低频Visa2000解调" },
    { 0, "低频Visa2000读取器" },
    { 0, "低频Visa2000克隆" },
    { 0, "低频Visa2000模拟" },
    { 1, "mem help" },
    { 0, "内存波特率" },
    { 0, "内存转储" },
    { 0, "内存信息" },
    { 0, "内存加载" },
    { 0, "内存擦除" },
    { 1, "mem spiffs help" },
    { 0, "SPIFFS复制" },
    { 0, "SPIFFS检查" },
    { 0, "SPIFFS转储" },
    { 0, "SPIFFS信息" },
    { 0, "SPIFFS挂载" },
    { 0, "SPIFFS删除" },
    { 0, "SPIFFS重命名" },
    { 0, "SPIFFS测试" },
    { 0, "SPIFFS树" },
    { 0, "SPIFFS卸载" },
    { 0, "SPIFFS上传" },
    { 0, "SPIFFS查看" },
    { 0, "mem spiffs wipe" },
    { 1, "mqtt help" },
    { 1, "MQTT发送" },
    { 1, "MQTT接收" },
    { 1, "nfc help" },
    { 1, "NFC解码" },
    { 0, "nfc type1 read" },
    { 1, "nfc type1 help" },
    { 0, "nfc type2 read" },
    { 1, "nfc type2 help" },
    { 0, "nfc type4a format" },
    { 0, "nfc type4a read" },
    { 0, "nfc type4a write" },
    { 0, "nfc type4a st25taread" },
    { 1, "nfc type4a help" },
    { 0, "nfc type4b read" },
    { 1, "nfc type4b help" },
    { 0, "nfc mf cformat" },
    { 0, "nfc mf cread" },
    { 0, "nfc mf cwrite" },
    { 0, "nfc mf pread" },
    { 1, "nfc mf help" },
    { 0, "nfc barcode read" },
    { 0, "nfc barcode sim" },
    { 1, "nfc barcode help" },
    { 1, "piv help" },
    { 0, "piv 选择" },
    { 0, "PIV获取数据" },
    { 0, "piv authsign" },
    { 0, "piv 扫描" },
    { 1, "piv list" },
    { 1, "smart help" },
    { 1, "smart list" },
    { 0, "智能暴力破解" },
    { 0, "智能卡信息" },
    { 1, "智能卡 PCSC" },
    { 0, "智能卡读卡器" },
    { 0, "智能卡原始命令" },
    { 1, "智能卡升级" },
    { 0, "智能卡设置时钟" },
    { 1, "script help" },
    { 1, "脚本列表" },
    { 1, "运行脚本" },
    { 1, "trace help" },
    { 1, "提取跟踪" },
    { 1, "列出跟踪" },
    { 1, "加载跟踪" },
    { 1, "保存跟踪" },
    { 1, "usart help" },
    { 0, "USART 蓝牙 PIN 码" },
    { 0, "USART 蓝牙恢复出厂设置" },
    { 0, "USART 发送" },
    { 0, "USART 接收" },
    { 0, "USART 收发" },
    { 0, "USART 十六进制发送" },
    { 0, "USART 十六进制接收" },
    { 0, "USART 配置" },
    { 1, "wiegand help" },
    { 1, "wiegand list" },
    { 1, "Wiegand 编码" },
    { 1, "Wiegand 解码" },
    { 0, "script run amiibo_change_uid.py" },
    { 0, "script run des_talk.py" },
    { 0, "script run findbits.py" },
    { 0, "script run fm11rf08s_full.py" },
    { 0, "script run fm11rf08s_recovery.py" },
    { 0, "script run hf_mfu_uscuid.py" },
    { 0, "script run ice.py" },
    { 0, "script run intertic.py" },
    { 0, "script run mf_backdoor_dump.py" },
    { 0, "script run mfuev1_counter_reset.py" },
    { 0, "script run mfulaes_mask_recovery.py" },
    { 0, "script run mfulc_counterfeit_recovery.py" },
    { 0, "script run ntag22x_libsuncmac.py" },
    { 0, "script run ntag22x_suncmac_recovery.py" },
    { 0, "script run parity.py" },
    { 0, "script run paxton_convert.py" },
    { 0, "script run paxton_net.py" },
    { 0, "script run paxton_switch.py" },
    { 0, "script run pm3.py" },
    { 0, "script run pm3_eml2mfd.py" },
    { 0, "script run pm3_eml_mfd_test.py" },
    { 0, "script run pm3_help2json.py" },
    { 0, "script run pm3_help2list.py" },
    { 0, "script run pm3_mfd2eml.py" },
    { 0, "script run pm3_nfc2eml.py" },
    { 0, "script run pm3_resources.py" },
    { 0, "script run read_t-union.py" },
    { 0, "script run spi_flash_decode.py" },
    { 0, "script run theremin.py" },
    { 0, "script run xorcheck.py" },
    { 0, "script run data_hex_crc.lua" },
    { 0, "script run data_mf_accessdecode.lua" },
    { 0, "script run data_mf_bin2eml.lua" },
    { 0, "script run data_mf_bin2html.lua" },
    { 0, "script run data_mf_eml2bin.lua" },
    { 0, "script run data_mf_eml2html.lua" },
    { 0, "script run data_mfu_bin2eml.lua" },
    { 0, "script run example_cmdline.lua" },
    { 0, "script run example_parameters.lua" },
    { 0, "script run hf_14a_aztek.lua" },
    { 0, "script run hf_14a_i2crevive.lua" },
    { 0, "script run hf_14a_protectimus_nfc.lua" },
    { 0, "script run hf_14a_raw.lua" },
    { 0, "script run hf_14a_read_ltocm.lua" },
    { 0, "script run hf_14b_calypso.lua" },
    { 0, "script run hf_14b_mobib.lua" },
    { 0, "script run hf_15_magic.lua" },
    { 0, "script run hf_i2c_plus_2k_utils.lua" },
    { 0, "script run hf_legic.lua" },
    { 0, "script run hf_legic_buffer2card.lua" },
    { 0, "script run hf_legic_clone.lua" },
    { 0, "script run hf_mf_autopwn.lua" },
    { 0, "script run hf_mf_dump_luxeo.lua" },
    { 0, "script run hf_mf_em_util.lua" },
    { 0, "script run hf_mf_format.lua" },
    { 0, "script run hf_mf_gen3_writer.lua" },
    { 0, "script run hf_mf_keycheck.lua" },
    { 0, "script run hf_mf_magicrevive.lua" },
    { 0, "script run hf_mf_mini_dumpdecrypt.lua" },
    { 0, "script run hf_mf_sim_hid.lua" },
    { 0, "script run hf_mf_tnp3_clone.lua" },
    { 0, "script run hf_mf_tnp3_dump.lua" },
    { 0, "script run hf_mf_tnp3_sim.lua" },
    { 0, "script run hf_mf_uid_downgrade.lua" },
    { 0, "script run hf_mf_uidbruteforce.lua" },
    { 0, "script run hf_mf_uidkeycalc.lua" },
    { 0, "script run hf_mf_uidkeycalc_mizip.lua" },
    { 0, "script run hf_mf_ultimatecard.lua" },
    { 0, "script run hf_mf_uscuid_prog.lua" },
    { 0, "script run hf_mfp_raw.lua" },
    { 0, "script run hf_mfu_amiibo_restore.lua" },
    { 0, "script run hf_mfu_amiibo_sim.lua" },
    { 0, "script run hf_mfu_magicwrite.lua" },
    { 0, "script run hf_mfu_pwdgen_italy.lua" },
    { 0, "script run hf_mfu_setuid.lua" },
    { 0, "script run hf_mfu_ultra.lua" },
    { 0, "script run hf_ndef_dump.lua" },
    { 0, "script run hf_ntag_3d.lua" },
    { 0, "script run hf_ntag_bruteforce.lua" },
    { 0, "script run hf_ntag_dt.lua" },
    { 0, "script run init_rdv4.lua" },
    { 0, "script run lf_awid_bulkclone.lua" },
    { 0, "script run lf_electra.lua" },
    { 0, "script run lf_em4100_bulk.lua" },
    { 0, "script run lf_em4x05_kybercrystals.lua" },
    { 0, "script run lf_em_tearoff.lua" },
    { 0, "script run lf_em_tearoff_protect.lua" },
    { 0, "script run lf_hid_bulkclone.lua" },
    { 0, "script run lf_hid_bulkclone_v2.lua" },
    { 0, "script run lf_ident_json.lua" },
    { 0, "script run lf_ioprox_bulkclone.lua" },
    { 0, "script run lf_t55xx_chk.lua" },
    { 0, "script run lf_t55xx_chk_date.lua" },
    { 0, "script run lf_t55xx_fix.lua" },
    { 0, "script run lf_t55xx_multiwriter.lua" },
    { 0, "script run lf_t55xx_reset.lua" },
    { 0, "script run mem_readpwd.lua" },
    { 0, "script run mem_spiffs_readpwd.lua" },
    { 0, "script run mfc_hammerlite.lua" },
    { 0, "script run multi_bruteforce.lua" },
    { 0, "script run ntag_clean.lua" },
    { 0, "script run ntag_getsig.lua" },
    { 0, "script run ntag_hammertime.lua" },
    { 0, "script run data_tracetest.lua" },
    { 0, "script run hf_read.lua" },
    { 0, "script run lf_t55xx_defaultask.lua" },
    { 0, "script run lf_t55xx_defaultbi.lua" },
    { 0, "script run lf_t55xx_defaultfsk.lua" },
    { 0, "script run lf_t55xx_defaultpsk.lua" },
    { 0, "script run lf_t55xx_writetest.lua" },
    { 0, "script run example.cmd" },
    { 0, "script run rdv4_init_extflash.cmd" },
    { 0, "script run test_psk_clone.cmd" },
    {0, NULL}
};

#ifdef __cplusplus
}
#endif

#endif
