#!/usr/bin/env python3
"""
apply_fast.py - Fast single-pass translation application.
Uses one regex per file: find ALL quoted strings, lookup in dict, replace if found.
Then build.
"""
import re, sys, os, subprocess, shutil, time, json

TRANS_FILE = "/tmp/cn2_to_translate.json"
ZH_FILE = "/tmp/zh_trans_cn2.py"
SRC_DIR = os.path.expanduser("~/pm3_cn2/client/src")
BUILD_DIR = os.path.expanduser("~/pm3_cn2")
OUTPUT_BIN = os.path.expanduser("~/pm3_cn2/client/proxmark3")
WIN_DIR = "/mnt/c/Users/Samso/OneDrive/Desktop/Projects/promark3/proxmark3-cn2-4.21611/client/"

BLACKLIST = {
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
    "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "default", "return", "break", "case", "const", "continue",
    "do", "else", "enum", "extern", "for", "goto", "if",
    "register", "sizeof", "static", "struct", "switch", "typedef",
    "union", "volatile", "while", "void", "int", "char", "long",
    "short", "float", "double", "unsigned", "signed", "auto",
    "true", "false", "NULL", "nullptr",
    "OK", "ok", "Done",
    "hf", "lf", "hw", "mf", "em",
    "csv", "json", "xml", "bin", "txt", "hex", "raw",
    "USB", "UART", "SPI", "I2C", "JTAG", "SWD",
    "ARM", "MCU", "FPGA", "LED", "ADC", "DAC",
    "NOLF", "END", "START",
}

def load_translations():
    """Load from generated Python file via exec or directly from JSON."""
    trans = {}
    # Try loading the Python file (generated by translate_async.py)
    with open(ZH_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    ns = {}
    exec(compile(content, ZH_FILE, 'exec'), ns)
    return ns.get('translations', {})

def apply_to_file(filepath, trans):
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
    except:
        return 0
    
    count = 0
    
    def replacer(m):
        nonlocal count
        inner = m.group(1)
        if inner in trans:
            chn = trans[inner]
            if chn and chn != inner and inner not in BLACKLIST and len(inner) >= 3:
                count += 1
                return '"' + chn + '"'
        return m.group(0)
    
    pattern = re.compile(r'"((?:[^"\\]|\\.)*)"')
    new_content = pattern.sub(replacer, content)
    
    if count > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
    
    return count

def main():
    print("Loading translations...")
    t0 = time.time()
    translations = load_translations()
    print(f"Loaded {len(translations)} translations in {time.time()-t0:.1f}s")
    
    # Filter
    t = translations
    print(f"Ready: {len(t)} entries")
    
    print("\nApplying translations...")
    t0 = time.time()
    total = 0
    files_changed = 0
    
    for root, dirs, files in os.walk(SRC_DIR):
        for f in sorted(files):
            if not f.endswith('.c') and not f.endswith('.h'):
                continue
            fp = os.path.join(root, f)
            n = apply_to_file(fp, t)
            if n > 0:
                files_changed += 1
                total += n
                if n > 50:
                    print(f"  {f}: {n}")
    
    print(f"\nTotal: {total} replacements in {files_changed} files ({time.time()-t0:.1f}s)")
    
    if "build" in sys.argv:
        print("\nBuilding...")
        os.chdir(BUILD_DIR)
        result = subprocess.run(["make", "-j4", "client"], capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print("BUILD FAILED!")
            err = (result.stderr or result.stdout).split('\n')
            for line in err[-20:]:
                if line.strip():
                    print(f"  {line}")
            return
        
        size = os.path.getsize(OUTPUT_BIN) // 1024
        print(f"Build OK: {OUTPUT_BIN} ({size} KB)")
        
        os.makedirs(WIN_DIR, exist_ok=True)
        dest = WIN_DIR + "proxmark3_cn2"
        shutil.copy2(OUTPUT_BIN, dest)
        print(f"Copied to: {dest}")
    else:
        print("Skipping build (add 'build' arg to compile)")

if __name__ == "__main__":
    main()
